apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dress-dock-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dress-dock-server
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dress-dock-client
                port:
                  number: 80