apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # MongoDB URI pointing to the internal kubernetes service
  uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZHJlc3MtZG9jay1mbG93
  # JWT Secret for authentication (base64 encoded)
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbi0xMjM0NQ==